---
abstract: 'A Catalyst view for R'
author:
  - 'Eriam Schaffter <eriam@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-R
no_index:
  directory:
    - t
    - inc
requires:
  Catalyst::View::TT: 0
  File::Slurp: 0
  Statistics::R: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
version: 0.01_2
